[package]
name = "nav-types"
version = "0.2.0"
authors = ["Jørgen Nordmoen <nordmoen90@gmail.com>"]
description = "Easily work with global positions and vectors"

homepage = "https://github.com/nordmoen/nav-types"
repository = "https://github.com/nordmoen/nav-types.git"

keywords = ["nav", "navigation", "ecef", "latitude", "wgs84"]
license = "MIT"

[dependencies]
clippy = { version = "0.0.82", optional = true }
nalgebra = "0.8.2"
num-traits = "0.1.34"

[dev-dependencies]
assert = "0.7.1"
quickcheck = "0.3.1"

[features]
default = []
dev = ["clippy"]
